#if defined _rezp_version_included
	#endinput
#endif
#define _rezp_version_included

/**
 * Re Zombie Plague version.
 */
#define REZP_VERSION_MAJOR		"%VERSION_MAJOR%"
#define REZP_VERSION_MINOR		"%VERSION_MINOR%"
#define REZP_VERSION_PATCH		"%VERSION_PATCH%"
#define REZP_VERSION_SHA		"%VERSION_SHA%"
#define REZP_VERSION_STR		REZP_VERSION_MAJOR + "." + REZP_VERSION_MINOR + "." + REZP_VERSION_PATCH
